
export enum MovieStatusEnum {
  RELEASED = "RELEASED",
  POST_PRODUCTION = "POST_PRODUCTION",
  IN_PRODUCTION = "IN_PRODUCTION",
  PLANNED = "PLANNED",
  CANCELED = "CANCELED",
  RUMORED = "RUMORED",
}
