export const ErrorCode = {
  INVALID_EMAIL: "INVALID_EMAIL",
  INVALID_PASSWORD: "INVALID_PASSWORD",
  INVALID_URL: "INVALID_URL",
  INVALID_UUID: "INVALID_UUID",
  INVALID_NON_NEGATIVE_INT: "INVALID_NON_NEGATIVE_INT",
  INVALID_NON_NEGATIVE_NUMBER: "INVALID_NON_NEGATIVE_NUMBER",
  INVALID_AGE_RATING: "INVALID_AGE_RATING",
  INVALID_MOVIE_STATUS: "INVALID_MOVIE_STATUS",
  INVALID_IMAGE_MIME_TYPE: "INVALID_IMAGE_MIME_TYPE",
  EMAIL_ALREADY_IN_USE: "EMAIL_ALREADY_IN_USE",
  INVALID_MOVIE_QUERY: "INVALID_MOVIE_QUERY",
  MOVIE_NOT_FOUND: "MOVIE_NOT_FOUND",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  TOKEN_INVALID: "TOKEN_INVALID",
  TOKEN_REVOKED: "TOKEN_REVOKED",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  RESET_TOKEN_EXPIRED: "RESET_TOKEN_EXPIRED",
  RESET_TOKEN_INVALID: "RESET_TOKEN_INVALID",
  INVALID_RATING: "INVALID_RATING",
  MOVIE_LIST_NOT_FOUND: "MOVIE_LIST_NOT_FOUND",
  UNAUTHORIZED: "UNAUTHORIZED",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR"
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
