export enum ErrorCode {
  INVALID_EMAIL = "INVALID_EMAIL",
  INVALID_PASSWORD = "INVALID_PASSWORD",
  INVALID_URL = "INVALID_URL",
  INVALID_UUID = "INVALID_UUID",
  INVALID_NON_NEGATIVE_INT = "INVALID_NON_NEGATIVE_INT",
  INVALID_NON_NEGATIVE_NUMBER = "INVALID_NON_NEGATIVE_NUMBER",
  INVALID_AGE_RATING = "INVALID_AGE_RATING",
  INVALID_MOVIE_STATUS = "INVALID_MOVIE_STATUS",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  INVALID_MOVIE_QUERY = "INVALID_MOVIE_QUERY",
  MOVIE_NOT_FOUND = "MOVIE_NOT_FOUND",
}
